#!/bin/bash
#run

PROCESS_LIMIT=3
HOME=/if10/den4gr
WORKING_DIR=$HOME/hulkdeer/research/SL/trunk/Newell
CELL_DIR=$WORKING_DIR/examples/cell
REMOTE_SCRIPT=$HOME/scripts/remote.sh
OMP_MACHINES=$WORKING_DIR/machinefile.openmp
CUDA_MACHINES=$WORKING_DIR/machinefile.cuda
MPI_MACHINES=$WORKING_DIR/machinefile
iterations=32
echo -e "***** BEGIN MPI *****\n" 
for ((p=3; p <= PROCESS_LIMIT ; p++))
do
  for data_size in 64
  do
    for pyramid_height in 1
    do
    echo -e "data_size,num_processes,pyramid_height,blocks_per_dimension,load_balance,device_setting"
      for blocks_per_dimension in 4 
      do
        balance=1
        for gpu_cpu_config in 3
        do
          echo -e "$data_size,$p,$pyramid_height,$blocks_per_dimension,$balance,$gpu_cpu_config,"

          mpiexec -n $p -disable-hostname-propagation -machinefile $CELL_DIR/machinefile $CELL_DIR/distributedCell $data_size $data_size $data_size $iterations $pyramid_height $blocks_per_dimension $balance $gpu_cpu_config
        done
      done
    done
  done
done
echo -e "***** END MPI *****\n"
