#!/bin/bash
#run

PROCESS_LIMIT=3
HOME=/af21/den4gr
WORKING_DIR=$HOME/hulkdeer/research/SL/trunk/Newell
CELL_DIR=$WORKING_DIR/examples/cell
REMOTE_SCRIPT=$HOME/scripts/remote.sh
OMP_MACHINES=$WORKING_DIR/machinefile.openmp
CUDA_MACHINES=$WORKING_DIR/machinefile.cuda
MPI_MACHINES=$WORKING_DIR/machinefile
iterations=64
pyramid_height=2
echo -e "***** BEGIN MPI *****\n" 
for ((p=2; p <= PROCESS_LIMIT ; p++))
do
  for data_size in 256 192 128
  do
    echo -e "data_size\tnum_processes\tblocks_per_dimension\tload_balance\tdevice_setting"
    for blocks_per_dimension in  4 8
    do
      for balance in 0 1
      do
        for gpu_cpu_config in 0 1 2
        do
          echo -e "$data_size,\t$p,\t$blocks_per_dimension,\t$balance,\t$gpu_cpu_config"
          
          mpirun -np $p -machinefile $WORKING_DIR/machinefile -x LD_LIBRARY_PATH $CELL_DIR/distributedCell $data_size $data_size $data_size $iterations $pyramid_height $blocks_per_dimension $balance $gpu_cpu_config
        done
      done
    done
  done
done
echo -e "***** END MPI *****\n"
