#!/bin/bash
#run

WEAK_LIMIT=4
STRONG_LIMIT=2
HOME=/af21/den4gr
WORKING_DIR=$HOME/hulkdeer/research/SL/trunk/Newell
HOTSPOT_DIR=$WORKING_DIR/examples/hotspot
REMOTE_SCRIPT=$HOME/scripts/remote.sh
echo -e "***** BEGIN OPENMP *****\n" 
for q in 64 128 256 512 1024
do
  echo -e "***** BEGIN STRONG ITERATION $q *****\n" 
  $REMOTE_SCRIPT $WORKING_DIR/machinefile.openmp $HOTSPOT_DIR/ompHotspot 2000 $q
  echo -e "***** END STRONG ITERATION   $q *****\n" 
done
echo -e "***** END OPENMP *****\n" 

echo -e "***** BEGIN CUDA *****\n" 
for q in 64 128 256 512 1024
do
  echo -e "***** BEGIN STRONG ITERATION $q *****\n" 
  $REMOTE_SCRIPT $WORKING_DIR/machinefile.cuda $HOTSPOT_DIR/cudaHotspot 2000 $q
  echo -e "***** END STRONG ITERATION   $q *****\n" 
done
echo -e "***** END CUDA *****\n" 

echo -e "***** BEGIN MPI *****\n" 
for ((p=1; p <= WEAK_LIMIT ; p++))
do
  echo -e "***** BEGIN WEAK ITERATION $p *****\n" 
  mpirun -np $p -machinefile $WORKING_DIR/machinefile -x LD_LIBRARY_PATH $HOTSPOT_DIR/distributedHotspot 2000 128
  echo -e "***** END WEAK ITERATION   $p *****\n" 
done

for q in 64 128 256 512 1024
do
  echo -e "***** BEGIN STRONG ITERATION $q *****\n" 
  mpirun -np $STRONG_LIMIT -machinefile $WORKING_DIR/machinefile -x LD_LIBRARY_PATH $HOTSPOT_DIR/hotspot 2000 $q
  echo -e "***** END STRONG ITERATION   $q *****\n" 
done
echo -e "***** END MPI *****\n" 
